In [74]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [31]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
pd.__version__

'2.3.1'

In [32]:
df.count()

engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

In [33]:
row_count = len(df)

In [34]:
row_count

9704

In [10]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [35]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [46]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [15]:
df[['fuel_efficiency_mpg']].max()

fuel_efficiency_mpg    25.967222
dtype: float64

In [9]:
asian_cars = df[df['origin'] == 'Asia']

In [11]:
max_mpg_asia = asian_cars['fuel_efficiency_mpg'].max()

In [12]:
max_mpg_asia

np.float64(23.759122836520497)

In [45]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  9704.000000     9704.000000   
mean            199.708368       3.962481   149.828215     3001.280993   
std              49.455319       1.999323    28.775248      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   131.000000     2666.248985   
50%             200.000000       4.000000   152.000000     2993.226296   
75%             230.000000       5.000000   168.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [38]:
df['horsepower'].median()

np.float64(149.0)

In [39]:
# Calculate the mode of the 'horsepower' column
most_frequent_horsepower = df['horsepower'].mode()

In [16]:
most_frequent_horsepower 

0    152.0
Name: horsepower, dtype: float64

In [40]:
mode_horsepower = df['horsepower'].mode()[0]

In [41]:
mode_horsepower

np.float64(152.0)

In [44]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [43]:
df['horsepower'].fillna(method =mode_horsepower, inplace=True)

/tmp/ipykernel_5326/2365756458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(method =mode_horsepower, inplace=True)


ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got 152.0

In [48]:
 df['horsepower'].median()



np.float64(152.0)

In [50]:
#Sum of weights (1 point)

In [55]:
#Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the sum of all the elements of the result? 

SyntaxError: unterminated string literal (detected at line 4) (1752190831.py, line 4)

In [56]:
asian_cars = df[df['origin'] == 'Asia']

In [64]:
asian_cars1 =  asian_cars[['vehicle_weight','model_year']].head(7)

In [65]:
asian_cars1

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [66]:
# Get the underlying NumPy array, X
X = asian_cars1.to_numpy()

In [67]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [68]:
print(X)
print(type(X))

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]
<class 'numpy.ndarray'>


In [69]:
# Calculate the transpose of X
XT = X.T


In [70]:
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [71]:
# Compute the matrix-matrix multiplication: XTX = X.T @ X
XTX = XT @ X

In [72]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [75]:
    XTX_inverted = np.linalg.inv(XTX)

In [76]:
XTX_inverted 

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [77]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [78]:
y


array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [79]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = XTX_inverted  @ X.T @ y

In [80]:
w

array([0.01386421, 0.5049067 ])

In [81]:
sum_of_w = np.sum(w)

In [82]:
sum_of_w

np.float64(0.5187709081074016)