In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a= np.array([1,2,3,5,7,12])

In [8]:
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]


np.int64(3)

In [10]:
a


array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[0]

np.int64(1)

In [12]:
a[2]=10
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [24]:
n


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n[0,1] = 20

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[2] = [1,1,1]

In [28]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [29]:
n[2,1]

np.int64(1)

In [30]:
n[:,1]

array([20,  5,  1])

In [31]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [33]:
n[:,2]

array([3, 6, 1])

In [34]:
n[:2]

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [35]:
n[:,2] = [0,1,2]

In [36]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [40]:
% Randomlg generated array

UsageError: Line magic function `%` not found.


In [37]:
np.random.rand(5,2)

array([[0.30701314, 0.64282184],
       [0.82137985, 0.41225732],
       [0.82439954, 0.27987704],
       [0.19941745, 0.55479109],
       [0.41464486, 0.23400745]])